### ISSUE TITLE
没有处理404

### ISSUE THREAD

**Issue by flyingnn** [vfasky/BlogCatke#5]
如果访问一个不存在的页面,应该是一个更加友好的页面,不要像这样:

http://qcoreblog.sinaapp.com/a

Traceback (most recent call last):
  File "/usr/local/sae/python/lib/python2.6/site-packages/tornado/web.py", line 949, in _execute
    self.prepare()
  File "/usr/local/sae/python/lib/python2.6/site-packages/tornado/web.py", line 1385, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

**Comment by vfasky** [comment]
已确认

**Comment by vfasky** [comment]
fix bug
